version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
    command: --max_connections=100 --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: spring-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      JWT_SECRET: mi_clave_super_segura_12345678901234567890
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
