# (BASE)
# Define configuraciones generales de la aplicacion
# Define qué perfil se activa por defecto
# No define base de datos ni configuraciones JPA/Hibernate específicas

# ===============================
# CONFIGURACION BASE
# ===============================
spring.application.name=springboot-crud
server.port=8085

# Perfil activo por defecto 
spring.profiles.active=mysql

# ===============================
# SPRINGDOC / SWAGGER 
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger






