# (PROD / Docker)
# Es para Docker o ejecucion en produccion con MySQL
# Se usa si se activa el perfil "mysql"

# ===============================
# DATABASE (MySQL) 
# ===============================   
spring.datasource.url=jdbc:mysql://mysql-db:3306/db_jpa_crud?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE 
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

# REDIS
spring.data.redis.host=redis
spring.data.redis.port=6379
