# (DEV)
# Se usa solo si el perfil activo es "h2"
# Carga automáticamente 

# =========================
# DATABASE - H2 
# =========================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# =========================
# H2 CONSOLE
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JPA OPEN IN VIEW
spring.jpa.open-in-view=false

# =========================
